= GoCD Pipeline Code DSL in Kotlin

image::https://api.travis-ci.org/1and1/gocd-pico-dsl.svg?branch=master[Latest Travis build from master,link=https://travis-ci.org/1and1/gocd-pico-dsl]

Generate GoCD pipelines for
link:https://github.com/tomzo/gocd-yaml-config-plugin[tomzo/gocd-yaml-config-plugin: Plugin to declare GoCD pipelines and environments configuration in YAML] in Kotlin DSL.

== Usage

=== Setup kotlin project with GoCD DSL as dependency

[source,xml]
.pom.xml
----
<build>
    <sourceDirectory>src/main/kotlin</sourceDirectory>
    <testSourceDirectory>src/test/kotlin</testSourceDirectory>
    <plugins>
        <plugin>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
<dependencies>
    <dependency>
        <groupId>net.oneandone.gocd</groupId>
        <artifactId>gocd-pico-dsl</artifactId>
        <version>0.3</version>
    </dependency>
</dependencies>
----

=== Define DSL

Define your pipelines with DSL. Call in a main function `ConfigSuite(gocd, outputFolder = Paths.get(outputFolder)).writeFiles()` to start generation.

.net.oneandone.gocd.picodsl.examples.MinimalExample.kt
[source,java]
----
fun main(args: Array<String>) {
    val gocd = gocd {
        pipelines {
            sequence {
                group("dev") {
                    pipeline("deploy") {
                        materials {
                            repoPackage("myArtifact")
                        }
                        template = Template("deploy", "last-stage")
                    }
                }
            }
        }
    }

    val outputFolder = if (args.isNotEmpty()) args[0] else "target/gocd-config"
    ConfigSuite(gocd, outputFolder = Paths.get(outputFolder)).writeFiles()
}
----

=== Generate DSL

Call the main function above via maven:

[source,bash]
----
mvn compile exec:java -Dexec.mainClass="net.oneandone.gocd.picodsl.samples.MinimalExampleKt" -Dexec.args="target/gocd-config"
----

=== Configure Exec Plugin in pom.xml

Have a look at link:examples[examples] for a working maven example.

The following snippet shows two kinds how pipelines can be generated. Using the config registry and `net.oneandone.gocd.picodsl.GeneratePipelinesKt` should be easier.

[source,xml]
.examples/pom.xml
----
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.6.0</version>
    <executions>
        <execution>
            <id>registry-starter</id>
            <phase>process-classes</phase>
            <goals>
                <goal>java</goal>
            </goals>
            <configuration>
                <!--ready to use starter which renders all registered pipelines -->
                <mainClass>net.oneandone.gocd.picodsl.GeneratePipelinesKt</mainClass>
                <arguments>
                    <argument>--sourcePackage=net.oneandone.gocd.picodsl.examples.registry</argument>
                    <argument>--plantuml</argument>
                    <argument>--dot</argument>
                </arguments>
            </configuration>
        </execution>
        <execution>
            <id>custom-starter</id>
            <phase>process-classes</phase>
            <goals>
                <goal>java</goal>
            </goals>
            <configuration>
                <!-- custom starter which calls ConfigSuite -->
                <mainClass>net.oneandone.gocd.picodsl.examples.MinimalExampleKt</mainClass>
            </configuration>
        </execution>
    </executions>
</plugin>
----

=== Using the registry

All objects which are derived from `RegisteredGocdConfig` are registered in `ConfigRegistry` and are automatically used by `net.oneandone.gocd.picodsl.GeneratePipelinesKt` if they are found in the defined base package.

[source,java]
.Second.kt
----
object Second : RegisteredGocdConfig({
    environments() {
        environment("devEnv") {}
    }
    pipelines {
        sequence {
            deploy("first") {
                group = "dev"
                materials {
                    repoPackage("euss")
                }
            }
        }
    }
})
----

